### ISSUE TITLE
SASS, LESS and CSS Coding Standard

### ISSUE THREAD

**Issue by sinakuhestani** [PHPallas/Standards#7]

**Comment by MuhammadA2006** [comment]
**HTML پیش پردازنده های**

**Html**, **Css**, **JavaScript**
میشه Cass, Pug  که شامل

که باعث : 1> کاهش کدنویسی میشه یعنی حذف کد های تکراری

که Extends, Mixins قابلیت های پیشرفته : 2> شامل
.است Cass مشابه


خوانایی بهتر : 3> سینتکس تمیزتر برای توسعه دهندگان

**جایگزین‌های مدرن**
 Web Components استفاده از المان‌های سفارشی  
<my-element>

**Comment by MuhammadA2006** [comment]
سلام سینا یک نمونه کوچیک درست کردم اگه خوبه، که کاملش رو بنویسم 🤔

**Comment by sinakuhestani** [comment]
@MuhammadA2006 منظور چیزی شبیه [این](https://github.com/PHPallas/Standards/blob/main/PHP/Coding-Standards.md) هست.

**Comment by sinakuhestani** [comment]
اگه دقت کنی میبینی نمونه کد و توضیحات داره. هر کدوم که میتونی رو کامیت کن.

**Comment by MuhammadA2006** [comment]
# استانداردهای کدنویسی SASS، LESS و CSS

## مقدمه
استانداردهای کدنویسی برای SASS، LESS و CSS برای حفظ یکپارچگی، خوانایی و قابلیت نگهداری کدهای استایل ضروری هستند. این سند دستورالعمل‌های اصلی برای نوشتن کدهای تمیز و کارآمد را ارائه می‌دهد.

## ساختار کلی

### سازماندهی فایل‌ها
- **ساختار پروژه**:
  ```
  styles/
  ├── base/
  │   ├── _reset.scss
  │   ├── _typography.scss
  │   └── _variables.scss
  ├── components/
  ├── layout/
  ├── pages/
  └── main.scss
  ```

- **فایل‌های partial** با underscore شروع می‌شوند (`_partial.scss`)
- فایل اصلی (main.scss) فقط شامل importها باشد

### تورفتگی و فاصله‌گذاری
- استفاده از **2 فاصله** برای تورفتگی (نه تب)
- یک خط خالی بین بلوک‌های قوانین
- عدم وجود فاصله قبل و بعد از پرانتزها در mixinها و توابع

## قراردادهای نامگذاری

### CSS
- نام کلاس‌ها با **kebab-case** (مثال: `.main-header`)
- استفاده از نام‌های معنادار و توصیفی
- اجتناب از نام‌های مرتبط با ظاهر (مثل `.blue-button`)

### SASS/LESS
- متغیرها: `$kebab-case` یا `@kebab-case`
- Mixins و توابع: `camelCase`
- Placeholders: `%kebab-case`

## متغیرها و تنظیمات

### تعریف متغیرها
```scss
// Good
$primary-color: #3498db;
$spacing-unit: 1rem;

// Bad
$primColor: #3498db;
```

- گروه‌بندی متغیرهای مرتبط
- قرار دادن متغیرها در فایل `_variables.scss`

## Nesting (تودرتو کردن)

### قوانین
- حداکثر **3 سطح تودرتو**
- استفاده از `&` برای حالت‌های pseudo و modifierها
```scss
// Good
.btn {
  &--primary {
    background: $primary-color;
   
    &:hover {
      background: darken($primary-color, 10%);
    }
  }
}

// Bad (nesting بیش از حد)
.header {
  .nav {
    ul {
      li {
        a {
          ...
        }
      }
    }
  }
}
```

## Mixins و توابع

### بهترین روش‌ها
- نام mixinها باید با فعل شروع شود
- توابع برای محاسبات استفاده شوند
```scss
// Good
@mixin center-element() {
  display: flex;
  justify-content: center;
  align-items: center;
}

@function calculate-rem($size) {
  @return $size / 16px * 1rem;
}
```

## سازماندهی کد

### ترتیب قوانین
1. متغیرهای محلی
2. قوانین @extend
3. قوانین @include
4. استایل‌های معمولی
5. Pseudo-classes و pseudo-elements
6. Media queries

```scss
.card {
  // 1. Variables
  $card-padding: 1rem;

  // 2. Extend
  @extend %box-shadow;

  // 3. Includes
  @include transition(all 0.3s ease);

  // 4. Regular styles
  padding: $card-padding;
  background: white;

  // 5. Pseudo-classes
  &:hover {
    transform: scale(1.05);
  }

  // 6. Media queries
  @media (max-width: 768px) {
    padding: $card-padding / 2;
  }
}
```

## کامنت‌گذاری

### استانداردها
- استفاده از کامنت‌های بلوکی برای بخش‌های اصلی
- کامنت‌های خطی برای توضیح قوانین پیچیده
```scss
/**
* Main navigation styles
* شامل استایل‌های برای منوی اصلی و آیتم‌های آن
*/
.nav {
  // حل مشکل تراز در مرورگرهای قدیمی
  display: flex;
}
```

## Media Queries

### روش توصیه شده
- استفاده از متغیر برای breakpointها
- رویکرد Mobile-first
```scss
$breakpoints: (
  'small': 576px,
  'medium': 768px,
  'large': 992px
);

@mixin respond-to($breakpoint) {
  @media (min-width: map-get($breakpoints, $breakpoint)) {
    @content;
  }
}

.column {
  width: 100%;
 
  @include respond-to('medium') {
    width: 50%;
  }
}
```

## بهینه‌سازی و عملکرد

### نکات کلیدی
- محدود کردن استفاده از `@extend` به placeholderها
- اجتناب از selectorهای بیش از حد خاص
- کاهش nestingهای غیرضروری
- استفاده از `%placeholder` برای قطعات کد قابل استفاده مجدد

## تفاوت‌های SASS و LESS

### SASS
- پشتیبانی از منطق پیچیده‌تر با `@if`، `@for`، `@each`
- امکان تعریف توابع سفارشی
- پشتیبانی از placeholder selectorها (`%placeholder`)

### LESS
- اجرا در سمت کلاینت با JavaScript
- سینتکس نزدیک‌تر به CSS استاندارد
- پشتیبانی از scope برای متغیرها

## نتیجه‌گیری
رعایت این استانداردها باعث ایجاد کدهای تمیز، قابل نگهداری و قابل توسعه می‌شود. تیم‌های توسعه باید این دستورالعمل‌ها را به صورت ثابت در تمام پروژه‌ها رعایت کنند تا همکاری بین اعضای تیم ساده‌تر شود و کیفیت کدها در طول زمان حفظ شود.
